# Generated by Django 6.0.3 on 2026-03-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0002_alter_student_current_rating_alter_student_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='educational_program',
            field=models.CharField(default='web technologies', max_length=255),
            preserve_default=False,
        ),
    ]
