# Generated by Django 6.0.3 on 2026-03-10 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0003_specialization_educational_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['id']},
        ),
    ]
