# Generated by Django 6.0.3 on 2026-03-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0004_alter_specialization_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='university_app.subject'),
        ),
    ]
