# Generated by Django 6.0.3 on 2026-03-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0005_alter_teacher_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='time_to_study',
            new_name='study_time',
        ),
    ]
