# Generated by Django 6.0.3 on 2026-03-18 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0006_rename_time_to_study_faculty_study_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='study_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='form_of_study',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('distance', 'Distance-learning')], max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
