# Generated by Django 6.0.3 on 2026-05-30 16:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0007_alter_faculty_study_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students_faculty', to='university_app.faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='form_of_study',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('distance', 'Distance-learning')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students_group', to='university_app.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students_specialization', to='university_app.specialization'),
        ),
    ]
